#
#
version: '3'

networks:
  kiva-network:
    external: true

services:
  protocol-gateway:
    env_file:
      - ./.env
    build:
      context: ./
    command: npm run start:debug # @todo want an easy way to switch between prod and dev
    image: protocol-gateway
    container_name: protocol-gateway
    working_dir: /www
    ports:
      - "8080:8080"
    expose: 
      - "8080"
    # I still haven't found the best way to do this, the idea is we want to load our source files from the host to allow
    # for rapid development but we need the node_modules build for the container
    # For now, any changes to package.json requires running:
    # docker exec -it auth-server npm install
    volumes:
      - ./:/www
      - node_modules:/www/node_modules
    networks:
      - kiva-network
    tty: true

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    networks:
      - kiva-network
  
volumes:
  node_modules:
