replicaCount: 2

image:
  repository: kivaprotocol/protocol-gateway
  tag: latest
  pullPolicy: Always
  imagePullSecrets:
    - name: "regcred"

nameOverride: "protocol-gateway"
fullnameOverride: "protocol-gateway"
secrets: "protocol-gateway-service-secrets"

strategy:
  type: "RollingUpdate"

service:
  type: ClusterIP
  port: 443
  containerPort: 8080
  targetPort: 8080
  portName: "https"

resources:
  limits:
    cpu: 1100m
    memory: 512Mi
  requests:
    cpu: 1100m
    memory: 256Mi

ingress:
  host: "gateway.protocol-dev.kiva.org"
  class: nginx-ingress-external
  tls: true

#tolerations:
#  - effect: NoSchedule
#    key: crypto
#    operator: Equal
#    value: "true"
#
#nodeSelector:
#    dedicated: crypto
